version: '3'

services:
  db:
    image: postgres:10.4
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
